version: 2.1

jobs:
  make-lint:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: Setting Up Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      
      - run:
          name: Installing hadolint, Pylint & Upgrading Pip
          command: |  
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
            pip install pylint
            pip install --upgrade pip
      
      - run:
          name: run lint 
          command: |
            . venv/bin/activate
            make lint 
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
  
  docker-upload:
    docker:
      - image: python:3.7.3-stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
          
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - setup_remote_docker:
        version: 19.03.13
      
      - run:
        name: containter version checkout
        command: |
          docker image ls
          docker ps -a
        
      - run:
        name: build docker containter
        command: |
          echo "--- Building Blue Deployment ---"
          docker build -t jralawrence/udacity-capstone-blue-deployment
          docker image ls
        
      - run:
        name: testing docker container 
        command: |
            docker run -d --rm --name testapp -p 8081:8080 jralawrence/udacity-capstone-blue-deployment
            sleep 5
            docker container ls
            docker stop testapp
      
      - run:
        name: uploading docker container
        command: |
          docker login -u = "$DOCKERHUB_USERNAME" -p = "$DOCKERHUB_PASSWORD"
          docker push jralawrence/udacity-capstone-blue-deployment
 
workflows:
  default:
    jobs:
      - make-lint
      - docker-upload:
        requires: [make-lint]
        